import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <nav>
          <ul>
            <li>
              <a href="/server-action/node">Node</a>
            </li>
            <li>
              <a href="/server-action/edge">Edge</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
